import type { Metadata } from "next";
import { Arsenal, Cormorant_Garamond } from "next/font/google";
import Image from "next/image";
import NavBar from "./ui/NavBar/NavBar";
import Sidebar from "./ui/SideBar/SideBar";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import "./globals.css";
import "./variables.css";
import styles from "./layout.module.css"
import KantImage from "@/app/images/Kant-image.jpg";
import { AuthProviderWrapper } from "./context/auth.context";

config.autoAddCss = false;

const garamond = Cormorant_Garamond({
  variable: "--main-font",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const arsenal = Arsenal({
  variable: "--notes-font",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Kritik der reinen Vernunft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${garamond.variable} ${arsenal.variable}`}>
          <div className={styles["App"]}>
            <div className={styles["side-cont"]}>
              <NavBar />
              <Image
                className={styles["kant-image"]}
                src={KantImage}
                alt="Immanuel Kant"
                title="Immanuel Kant"
                priority
                />
              <Sidebar />
            </div>
            <div className={styles["app-inner-cont"]}>
              <NavBar small />
              <AuthProviderWrapper>
                {children}
              </AuthProviderWrapper>
            </div>
          </div>
      </body>
    </html>
  );
}
